import type { RunReport } from "../shared/model"

export const showcaseReport: RunReport = {
  id: "showcase-orbit-1842",
  displayId: "FD-1842",
  source: "showcase",
  status: "failed",
  verdict: "HOLD — checkout interaction regressed",
  target: {
    repository: "https://github.com/sscode/solari-cookbook",
    pullNumber: 1,
    commit: "9a86e1f",
    projectPath: "projects/pr-flight-deck/fixtures/demo-shop",
  },
  createdAt: "2026-09-01T00:14:18.000Z",
  updatedAt: "2026-09-01T00:16:01.420Z",
  startedAt: "2026-09-01T00:14:19.000Z",
  finishedAt: "2026-09-01T00:16:01.420Z",
  durationMs: 102_420,
  previewUrl: "https://orbit-supply.preview.getsolari.com",
  stages: [
    {
      id: "allocate",
      label: "Isolate",
      status: "passed",
      detail: "2 vCPU sandbox restored from base template",
      durationMs: 1_184,
    },
    {
      id: "checkout",
      label: "Checkout",
      status: "passed",
      detail: "Fetched pull/1/head at 9a86e1f",
      durationMs: 4_902,
    },
    {
      id: "build",
      label: "Build",
      status: "passed",
      detail: "Static fixture prepared without host credentials",
      durationMs: 3_106,
    },
    {
      id: "preview",
      label: "Expose",
      status: "passed",
      detail: "Public preview healthy on port 4173",
      durationMs: 2_944,
    },
    {
      id: "desktop",
      label: "Desktop run",
      status: "failed",
      detail: "Primary checkout journey stopped at step 4",
      durationMs: 28_640,
    },
    {
      id: "mobile",
      label: "Mobile run",
      status: "failed",
      detail: "Regression reproduced at 390 × 844",
      durationMs: 31_012,
    },
    {
      id: "evidence",
      label: "Retain",
      status: "passed",
      detail: "Screenshots, replays, and failure snapshot retained",
      durationMs: 24_006,
    },
    {
      id: "cleanup",
      label: "Release",
      status: "passed",
      detail: "Browser sessions released; sandbox destroyed",
      durationMs: 6_626,
    },
  ],
  suites: [
    {
      id: "desktop",
      label: "Desktop Chrome",
      viewport: { width: 1440, height: 900 },
      status: "failed",
      durationMs: 28_640,
      consoleErrors: [],
      screenshotUrl: "/showcase/desktop.svg",
      replayEventCount: 1_284,
      checks: [
        {
          id: "desktop-http",
          category: "network",
          label: "Preview responds",
          status: "passed",
          detail: "HTTP 200 in 318 ms",
          durationMs: 318,
        },
        {
          id: "desktop-heading",
          category: "journey",
          label: "Storefront renders",
          status: "passed",
          detail: "Found “Orbital Supply”",
          durationMs: 74,
        },
        {
          id: "desktop-add",
          category: "journey",
          label: "Add navigation light",
          status: "passed",
          detail: "Button accepted the click",
          durationMs: 182,
        },
        {
          id: "desktop-cart",
          category: "journey",
          label: "Cart confirms selection",
          status: "failed",
          detail: "Expected “1 item secured”; counter remained at 0",
          durationMs: 5_002,
        },
        {
          id: "desktop-console",
          category: "runtime",
          label: "No console exceptions",
          status: "passed",
          detail: "No uncaught browser errors",
        },
        {
          id: "desktop-a11y",
          category: "accessibility",
          label: "Accessible names",
          status: "warning",
          detail: "One decorative SVG is missing aria-hidden",
        },
      ],
    },
    {
      id: "mobile",
      label: "Mobile Chrome",
      viewport: { width: 390, height: 844 },
      status: "failed",
      durationMs: 31_012,
      consoleErrors: [],
      screenshotUrl: "/showcase/mobile.svg",
      replayEventCount: 1_106,
      checks: [
        {
          id: "mobile-http",
          category: "network",
          label: "Preview responds",
          status: "passed",
          detail: "HTTP 200 in 401 ms",
          durationMs: 401,
        },
        {
          id: "mobile-layout",
          category: "runtime",
          label: "Viewport has no horizontal overflow",
          status: "passed",
          detail: "390 px layout fits without clipping",
        },
        {
          id: "mobile-heading",
          category: "journey",
          label: "Storefront renders",
          status: "passed",
          detail: "Found “Orbital Supply”",
          durationMs: 91,
        },
        {
          id: "mobile-add",
          category: "journey",
          label: "Add navigation light",
          status: "passed",
          detail: "Button accepted the tap",
          durationMs: 220,
        },
        {
          id: "mobile-cart",
          category: "journey",
          label: "Cart confirms selection",
          status: "failed",
          detail: "Expected “1 item secured”; counter remained at 0",
          durationMs: 5_003,
        },
      ],
    },
  ],
  summary: {
    passed: 8,
    failed: 2,
    warnings: 1,
    total: 11,
  },
  environment: {
    sandboxTemplate: "base",
    snapshotRetained: true,
    cleanup: "complete",
  },
  logs: [
    {
      at: "2026-09-01T00:14:20.184Z",
      stage: "allocate",
      stream: "system",
      message: "Sandbox ready in 1.18 s",
    },
    {
      at: "2026-09-01T00:14:25.086Z",
      stage: "checkout",
      stream: "stdout",
      message: "Checked out pull/1/head at 9a86e1f",
    },
    {
      at: "2026-09-01T00:14:31.136Z",
      stage: "preview",
      stream: "system",
      message: "Preview returned HTTP 200",
    },
    {
      at: "2026-09-01T00:15:04.812Z",
      stage: "desktop",
      stream: "stderr",
      message: "Expected “1 item secured”; counter remained at 0",
    },
    {
      at: "2026-09-01T00:15:36.006Z",
      stage: "mobile",
      stream: "stderr",
      message: "Regression reproduced at 390 × 844",
    },
    {
      at: "2026-09-01T00:16:01.420Z",
      stage: "cleanup",
      stream: "system",
      message: "All remote resources released",
    },
  ],
}
